# ask for the heightmap of the square of water surface at (x,y), with given size and resolution
float32 x 0.
float32 y 0.
float32 theta 0.
float32 resolution 0.1
float32 size 2.
---
# returns x-major (dim x dim) surface starting at (-size/2,-size/2) in relative frame
int32 dim
float32[] surface
